language: cpp

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libxaw7-dev

compiler:
  - clang
  - gcc

env:
  - CMAKE_BUILD_TYPE=Debug
  - CMAKE_BUILD_TYPE=Release

script:
  - mkdir build
  - cd build
  - cmake -D CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} .. && make
